### ISSUE TITLE
Memory use and issues with fold change output

### ISSUE THREAD

**Issue by SofieHvid** [Center-for-Health-Data-Science/BulkDGD#7]
Hi, 
We have two questions / issues at hand.

1) 
We have been using bulkDGD on another dataset, with a fairly large sample size of approx. 10.000.  When attempting to run bulkDGD on all samples at once, we quickly run out of memory (> 200 gb). We have instead attempted to process fewer samples at a time which requires significantly less memory but takes longer time. Is this to be expected? And is our approach compatible with your code?

2) 
The other issue we are dealing with is the fold change output from the DEA is oddly distributed. It seems to have some weird cut offs. Do you have a suggestion as to what could have gone wrong? The issue is illustrated on the figure below, where we have a comparison of the log fold changes computed using the mean expression of our entire dataset vs using bulkDGD.

![3125a366-b509-4aee-8e4e-1f40baeac1ab](https://github.com/Center-for-Health-Data-Science/bulkDGD/assets/125875120/388463bd-8878-48f1-aff7-d1e963e9539e)

**Comment by iprada** [comment]
Hi Sofie, 

Regarding splitting the samples into small batches, your approach is definitely compatible. Regarding longer runtimes, that is probably expected, but I would need to know how long is "longer time" w.r.t to running the entire dataset.

Regarding the log fold-changes: That looks odd, I agree. In order to figure out what happened, can you give some details about how you run dgd?

best,

Iñigo

**Comment by SofieHvid** [comment]
It takes about 3.5 hours to process the entire dataset.

We run dgd as done in the tutorials, without changing anything but the input. We input our raw count expression matrix  (spliced into smaller sample sizes) instead and followingly 'restack' the output before saving, else nothing is changed. Likewise we compute the log fold change as shown in the second tutorial. 

Thank you for the fast response.

**Comment by iprada** [comment]
good. thank you.

We will give it a look. It is worth stating that I have never seen bulkDGD produce mostly positive log fold changes.

We will get back to you. It might take some time.

best,

Iñigo

**Comment by SofieHvid** [comment]
That sounds great, thank you.

Regarding the issue, it seems as if the variable `pred_means` does not get rescaled when using the function `perform_dea` to compute the log2 fold changes only, and instead uses the decoder output directly as `pred_means`. Is this correct? 
It appears as if the `pred_means` only gets scaled if the `get_p_values` method also gets called.

**Comment by ValeSora** [comment]
@iprada is what SofieHvis reporting expected behavior for the log2 fold changes calculation? Otherwise, I'll implement the rescaling.

**Comment by ValeSora** [comment]
Hi @SofieHvid! We found the problem, and we are working on fixing it. I'm going to ping you here as soon as it's solved.

**Comment by ValeSora** [comment]
@SofieHvid, the issue should be resolved now! Let us know whether you encounter any more issues.

**Comment by SofieHvid** [comment]
Sounds good!
